include: package:very_good_analysis/analysis_options.11.0.0.yaml

analyzer:
  errors:
    document_ignores: ignore
  exclude:
    - build/**
    - web/**
    - linux/**

linter:
  rules:
    public_member_api_docs: false
