name: example
description: Dashbook example

version: 1.0.0+1

publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0" # dart version

dependencies:
  alkami_core_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0

  flutter:
    sdk: flutter

  dashbook:
    path: ../


dev_dependencies:
  alkami_core_dev_dependencies: 
    hosted: https://dart.cloudsmith.io/alkami/flutter/
    version: ^2.1.0

flutter:
  uses-material-design: true
