include: package:very_good_analysis/analysis_options.2.4.0.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_constructors_first: false
    avoid_positional_boolean_parameters: false
    only_throw_errors: false
    avoid_returning_this: false
    prefer_function_declarations_over_variables: false
    no_logic_in_create_state: false