name: gallery
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  dashbook: ^0.1.13
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
