name: Validate PR is Ready for Merge

env:
  dart_version: 2.18.6
  flutter_version: 3.3.10
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
  JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main
      - release/**

jobs:
  pr_validation:
    name: Validate Pull Request is Ready for Merge
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: false
          token: '${{ secrets.GH_ACTIONS_PAT }}'

      - name: Cache Flutter dependencies
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ env.flutter_version }}-flutter

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: 'stable'

      - name: Git Config Update
        run: git config --global url."https://x-token-auth:${{ secrets.GH_ACTIONS_PAT }}@github.com".InsteadOf https://github.com

      - name: Authorize Cloudsmith
        run:  ./shell_scripts/authorize_cloudsmith.sh ${{ secrets.CLOUDSMITH_API_KEY }}

      - name: Pub get
        run: flutter pub get

      - name: Validate PR is ready
        run: dart pub run mplat_pr_tools validatePRIsReadyForMerge --minCoverage 0 --no-publishDryRun --no-test --no-generateCoverage
