name: Tag release
on:
  push:
    branches: [main]

jobs:
  publish-packages:
    name: Create tags for release
    permissions:
      actions: write
      contents: write
    runs-on: [ ubuntu-latest ]
    if: contains(github.event.head_commit.message, 'chore(release)')
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
      - uses: bluefireteam/melos-action@v3
        id: melos
        with:
          tag: true
      - name: Trigger publish for the new tags
        run: |
          for tag in $TAGS; do
            gh workflow run release-publish.yml --ref "$tag"
          done
        env:
          TAGS: ${{ steps.melos.outputs.tags }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
